
# Generated by Django 4.2.6 on 2023-10-28 18:25


from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (posts.models.SNSType["FACEBOOK"], "facebook"),
                            (posts.models.SNSType["INSTAGRAM"], "instagram"),
                            (posts.models.SNSType["THREAD"], "thread"),
                            (posts.models.SNSType["TWITTER"], "twitter"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HashTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to="posts.posts"
                    ),
                ),
            ],
        ),
    ]
