# Generated by Django 4.2.6 on 2023-10-27 17:52
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="아이디"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="이메일"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "activation_code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="인증코드"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},

        ),
    ]
